---
- hosts: all
  become: true
  gather_facts: true


  vars_files:
    - group_vars/vars.yml

  tasks:

# Role 1 - Linux fresh minimal install
  # Update the OSs and reboot them
    - name: Update the OS
      package:
        name: "*"
        state: latest

    - name: Reboot after updates
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: Wait for 10 seconds for system startup
      pause:
        seconds: 10

    - name: Wait for instance reboot
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 60


    # Verify that desktop env's exist and install them if they don't

    - name: Verify desktop environment is installed
      package_facts:
        manager: "auto"
      register: desktop

    - name: Ubuntu - install desktop environment and necessary packages
      package:
        name: ubuntu-desktop
        state: latest
      when: 'ubuntu-desktop' not in ansible_facts.packages and ansible_distribution == "Ubuntu"

    - name: CentOS - install desktop environment and necessary packages
      package:
        name: GNOME Desktop
        state: latest
      when: 'GNOME Desktop' not in ansible_facts.packages and ansible_distribution == "CentOS"

    - name: CentOS - desktop config
      shell: echo "exec gnome-session" >> ~/.xinitrc && sudo systemctl set-default graphical.target


# Role 2 - Linux - Install CAS agents and necessary packages
    # Install required packages
    - name: Ubuntu - install required packages
      package:
        - name: "{{ item }}"
        - state: latest
      with_items:
        - usb-vhci-dkms
      when: ansible_distribution == "Ubuntu"

    - name: CentOS - install required packages
      package:
        - name: "{{ item }}"
        - state: latest
      with_items:
        - usb-vhci
      when: ansible_distribution == "CentOS"

    # Install CAS agent
    - name: Ubuntu - install Teradici repo
      apt:
        name: https://downloads.teradici.com/ubuntu/teradici-repo-$(lsb_release -cs)-latest.deb
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Ubuntu - install standard agent
      apt:
        name: pcoip-agent-standard
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: CentOS - install Teradici repo
      yum:
        name: https://downloads.teradici.com/rhel/teradici-repo-latest.noarch.rpm
        state: present
      when: ansible_distribution == "CentOS"

    # Register the agent
    - name: Register the agent
      shell: "pcoip-register-host --registration-code={{ reg_code }}"

    #

# Role 3 - Windows


